server:
  port: 8080

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: jieyi123
    url: jdbc:mysql://10.34.34.73:3306/qiniu-collector?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource
  # Spring 配置；rabbitmq
  rabbitmq:
    addresses: 10.34.34.73
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch: 10 # 每次投递n个消息，消费完在投递n个
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000 # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
    topic:
      field: field
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml
# MyBatis Plus配置
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔com.sdwu.infrastructure.persistent.dao.Xxx
  typeAliasesPackage: com.sdwu.**.**.po
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:/mybatis/mapper/*.xml
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
      logic-delete-field: deleted
    banner: false
  # 加载原生全局的配置文件
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
redis:
  sdk:
    config:
      host: 10.34.34.73
      port: 6379
      password: jieyi123
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 6
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
# OpenAi 配置；ChatGPT、ChatGLM..
dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    minio:
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: 03QlKvulEFSYIBhloq6a
        secret-key: CTqRtyLHtGWREUYLGNoN2NcZ4d7yXomfulTMpDEr
        end-point: http://10.34.34.73:9900
        bucket-name: paper
        domain: http://10.34.34.73:9900/paper/ # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: paper/ # 基础路径
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: LTAI5tM8kNgNwqtqpRUXhjpR
        secret-key: HTbYYenrCN1mejKw5t2KLhNpEsdZyv
        end-point: oss-cn-hangzhou.aliyuncs.com
        bucket-name: ftdb-gatsbyh-open
        domain: https://ftdb-gatsbyh-open.oss-cn-hangzhou.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: paper/ # 基础路径

# OpenAi 配置；ChatGPT、ChatGLM...
openai:
  sdk:
    config:
      enabled: true
      moonshot:
        #        # 状态；true = 开启、false 关闭
        enabled: true
        # 官网地址
        api-host: https://api.moonshot.cn/
        # 官网申请 https://open.bigmodel.cn/usercenter/apikeys
        api-key: sk-6iJzBNQib9q0Oiym0uyk4Kvtvta7JOmEsyqsM4xbDFV6RLuu
      chatglm:
        api-host: https://open.bigmodel.cn/
        api-key: 2589ec5698aa22ce677a261bb7bf5221.nCX8m9P7dfLKUBdp
        enabled: true
